### PR TITLE
On Android M Surfaceflinger passes fb0 for name

### PR DESCRIPTION
**Pull request by harishkrupo**
On Android M Surfaceflinger opens the gralloc module with
the name fb0

Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Comment by harishkrupo** [comment]
@kalyankondapally

**Comment by tpalli** [comment]
So I suppose there is still artificial dependency on framebuffer HAL in M but that is not used because we have HWC in place? I think this is fine if this is enough to make it work.

**Comment by tpalli** [comment]
Maybe good to add a comment that this is for M support in case someone wonders.

**Comment by harishkrupo** [comment]
> Maybe good to add a comment that this is for M support in case someone wonders.
Sure, will do that.

**Comment by kalyankondapally** [comment]
@harishkrupo I am in process of rebasing minigbm and will merge this along with it. Can you also try to get this upstreamed to chromiumos repository ?

**Comment by kalyankondapally** [comment]
Here is the rebased branch which will become master https://github.com/intel/minigbm/tree/rebase

**Pull request closed without merging**
