### PR TITLE
Update enum value of HAL_PIXEL_FORMAT_NV12 to 0x10F

### PR DESCRIPTION
**Pull request by JeevakaPrabu**
Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
Why would you do this? Note that upstream drm_gralloc uses 0x102.

**Comment by JeevakaPrabu** [comment]
@tpalli 
Issue:
In media driver, 0x102 corresponds to  HAL_PIXEL_FORMAT_YCrCb_422_H and 0x10F is HAL_PIXEL_FORMAT_NV12_LINEAR. If we map HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED to HAL_PIXEL_FORMAT_NV12(droid_format) in gralloc, then it is HAL_PIXEL_FORMAT_YCrCb_422_H in media driver.

So, there are 2 options:
1. Change the value of NV12 to 0x10F which corresponds to NV12 Linear format (or)
2. Introduce new format HAL_PIXEL_FORMAT_NV12_LINEAR with value 0x10F. This requires changes in gralloc and also in mesa. Note: In this case, DRM_FORMAT_NV12 will be mapped to HAL_PIXEL_FORMAT_NV12_LINEAR. So, HAL_PIXEL_FORMAT_NV12 will be defined but not used.

Let me know which option I can take or if you have any other better option, let me know.

**Comment by tpalli** [comment]
One option would be to use flexible format HAL_PIXEL_FORMAT_YCbCr_420_888 and android_ycbcr struct to describe the layout, this is what Mesa currently expects as it is a vendor neutral choice.

Media driver has been written against proprietary HAL module that defines enums against different driver. It is very likely that media driver needs to be fixed in order to work properly with open source components. If media driver cannot be changed, then only option is to add vendor specific enums like HAL_PIXEL_FORMAT_YCrCb_422_H, however I don't think upstream will accept such.

**Comment by kalyankondapally** [comment]
@xuguangxin Can you take this change into account in your side.

**Comment by kalyankondapally** [comment]
for now I have merged this to enable the domains, eventually want to clean up these non standard formats.

**Pull request closed without merging**
