### PR TITLE
Add the video format check

### PR DESCRIPTION
**Pull request by yhe39**
Change-Id: I4fec950e38c40de53e9b05ea6ca6713b39f5dbf7
Jira: OAM-82980
Test: Camera woeks well, no regrssion
Signed-off-by: HeYue <yue.he@intel.com>

### CODE REVIEW

**Comment by yhe39** [comment]
@js0701 @YuanjunHuang please help to review.
This is the wa for the camera doesn't work issue.
when use camera, the buffer format and descriptor format is not same. in validatebuffersize will cause return false and importbuffer fail, the camera doesn't work well.
Thanks!

**Comment by js0701** [comment]
What should be the correct fix instead of WA here?
Should we file a bug to camera team

**Comment by yhe39** [comment]
hi @js0701, maybe my expression is not precise, the camera case is special, the format of buffer and descriptor is not same, need special deal with. So add this patch to avoid the camera bug.
I think do not need file bug to camera team. Thanks!

**Comment by js0701** [comment]
Why for video we don't need to check format?

**Comment by yhe39** [comment]
hi, from the error log:

07-17 04:06:25.585  3034  5244 E Camera3-OutputStream: getBufferLockedCommon: Stream 1: Can't dequeue next output buffer: Unknown error -3 (3)
07-17 04:06:25.586  3034  5244 E CrosGralloc1 : hnd format is 842094158, after convert, is 943274297
07-17 04:06:25.586  3034  5244 E CrosGralloc1 : formate not equal
07-17 04:06:25.586  3034  5244 E GraphicBufferMapper: validateBufferSize(0xe68577e0) failed: 3
07-17 04:06:25.586  3034  5244 E GraphicBuffer: unflatten: registerBuffer failed: Unknown error -3 (3)
07-17 04:06:25.586  3034  5244 E Surface : dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: 3 
NV12 = 842094158  doesn't find what 943274297 is.
According to NV12 format, i submit this patch.

**Comment by js0701** [comment]
Can you add log in the validate function
1) What is the format of the handle
1) What is the format of the descriptor 
for this camera scenario

**Comment by yhe39** [comment]
sure, shaofeng helps to provide the method: DUMPTRACE("Preferred Video Format: %4.4s", (char*)&(prefered_video_format_));
i will add the char format log and update later.
Thanks

**Comment by yhe39** [comment]
hi @js0701 @YuanjunHuang , 
CrosGralloc1 : handle format is NV12, after convert descripitor format is 9998
in cros_gralloc_convert_format function, the descriptor goes the case:
        case HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED:
                 return DRM_FORMAT_FLEX_IMPLEMENTATION_DEFINED;
Thanks!

**Comment by js0701** [comment]
let's give WA only for HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED,
let HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED match any format?

**Comment by yhe39** [comment]
how about check the descriptor format, if the format is HAL_PIXEL_FORMAT_IMPLEMENTATION_DEFINED, skip the format check in validatebuffer size?
Thanks!

**Comment by js0701** [comment]
yes, please

**Comment by YuanjunHuang** [comment]
perhaps this should not be a wa. In Android, the FLEX means flexible YUV, so suggest to add a check-flex-format function. flexible format contains any of YUV format such as NV12, YV12, YUV420 ... here NV12 and DRM_FORMAT_FLEX_IMPLEMENTATION_DEFINED should consider as matched or equal.

**Comment by yhe39** [comment]
thanks @YuanjunHuang  and @js0701 , i will modify patch accordingly. :)

**Comment by yhe39** [comment]
Submit another patch to fix camera issue. close this wa patch. thanks!

**Pull request closed without merging**
