### PR TITLE
Added Support for 32bit RGB format

### PR DESCRIPTION
**Pull request by pyn1**
Jira: https://jira01.devtools.intel.com/browse/OAM-58928
Tests: Test Passes for the intended format
Signed-off-by: Poornima <poornima.y.n@intel.com>

### CODE REVIEW

**Comment by tpalli** [comment]
Note, commit message should mention already the format (no need to try to hide it?). As example: "Add support for HAL_PIXEL_FORMAT_RGBA_1010102".

**Comment by pyn1** [comment]
@tpalli Thanks for pointing. I have updated commit message now.

**Comment by pyn1** [comment]
@kalyankondapally, Please review.

**Comment by kalyankondapally** [comment]
merged

**Pull request closed without merging**
