### PR TITLE
Flick fix

### PR DESCRIPTION
**Pull request by JeevakaPrabu**
@bjbeare @kalyankondapally @harishkrupo

### CODE REVIEW

**Comment by tpalli** [comment]
Is there some Jira associated with this? What was flickering, everything?

**Comment by bjbeare** [comment]
Every second frame in the preview windows as a green-screen.

**Comment by kalyankondapally** [comment]
@JeevakaPrabu Can u open a Jira for this issue in this database: https://01.org/jira/browse/IAHWC-64  and we can discuss it there

**Comment by JeevakaPrabu** [comment]
@tpalli @bjbeare @kalyankondapally 
 https://01.org/jira/browse/AIA-433

**Pull request closed without merging**
