### PR TITLE
Enabling Render Buffer Compression in minigbm.

### PR DESCRIPTION
**Pull request by YuanjunHuang**
Add RBC modifier support.

Jira: https://jira01.devtools.intel.com/browse/AREQ-23273
Test: Build passes and validates with hwcomposer testlayer APP.

Signed-off-by: Yuanjun Huang <yuanjun.huang@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
Can we just use this patch https://chromium-review.googlesource.com/c/chromiumos/platform/minigbm/+/762186/2/i915.c ?

**Comment by YuanjunHuang** [comment]
yes. we can just use the patch from Chromium.

**Comment by kalyankondapally** [comment]
@YuanjunHuang Can you rebase the patch here and send PR ?

**Comment by YuanjunHuang** [comment]
@kalyankondapally New PR was already sent out. 
https://github.com/intel/minigbm/pull/52

**Pull request closed without merging**
